### ISSUE TITLE
Build with gcc5

### ISSUE THREAD

**Issue by awissu** [BlueBrain/DisplayCluster#261]
[  362s] /usr/include/deflect/MTQueue.h:88:16: error: converting to 'std::queue&lt;std::shared_ptr&lt;FFMPEGPicture&gt;, std::deque&lt;std::shared_ptr&lt;FFMPEGPicture&gt;, std::allocator&lt;std::shared_ptr&lt;FFMPEGPicture&gt; &gt; &gt; &gt;' from initializer list would use explicit constructor 'std::queue&lt;_Tp, _Sequence&gt;::queue(_Sequence&amp;&amp;) [with _Tp = std::shared_ptr&lt;FFMPEGPicture&gt;; _Sequence = std::deque&lt;std::shared_ptr&lt;FFMPEGPicture&gt;, std::allocator&lt;std::shared_ptr&lt;FFMPEGPicture&gt; &gt; &gt;]'
[  362s]          _queue = {};

See more: https://pmbs.links2linux.de/package/live_build_log/home:awissu:equalizer-qt5/DisplayCluster/openSUSE_Tumbleweed/x86_64

**Comment by eile** [comment]
We don't support gcc5 yet. Please submit a pull request if you fix the build, for us this is hard since we don't have the toolchain ready.
